# Generated by Django 5.0.7 on 2024-08-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_author_user_alter_book_pagination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')]),
        ),
    ]
