# Generated by Django 5.0.7 on 2024-08-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_alter_author_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')]),
        ),
    ]
